service: mfpv-discord

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  apiGateway:
    shouldStartNameWithService: true

functions:
  express:
    handler: src/handlers/expressHandler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  updateCommandsEvent:
    handler: src/handlers/updateCommandsHandler.handler
    events:
      - schedule: cron(10 4 * * ? *) # 10 minutes after mfpv-backup https://github.com/minecraft-fpv/mfpv-backup/blob/master/serverless.yml#L35
      - http:
          path: /update_commands
          method: ANY
  asyncDownload: # interactions must respond immediately. Async work is passed to this lambda.
    handler: src/handlers/asyncDownload.handler
    events:
      - http:
          path: /async_download
          method: ANY
          async: true
  asyncRestore: # interactions must respond immediately. Async work is passed to this lambda.
    handler: src/handlers/asyncRestore.handler
#    memorySize: 2048 # optional, in MB, default is 1024
    timeout: 120 # optional, in seconds
    events:
      - http:
          path: /async_restore
          method: ANY
          async: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  bundle:
    packager: yarn
  serverless-offline:
    httpPort: 4000