service: mfpv-discord

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  apiGateway:
    shouldStartNameWithService: true

functions:
  express:
    handler: src/handlers/expressHandler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  updateCommandsEvent:
    handler: src/handlers/updateCommandsHandler.handler
    events:
      - schedule: cron(10 4 * * ? *) # 10 minutes after mfpv-backup todo: link to mfpv-backup line in github.
      - http:
          path: /update_commands
          method: ANY

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  bundle:
    packager: yarn
  serverless-offline:
    httpPort: 4000